### ISSUE TITLE
cannot read ome-zarr from s3

### ISSUE THREAD

**Issue by d-v-b** [mobie/mobie-io#138]
Attempting to load the following dataset from s3 (`s3://janelia-cosem-datasets/jrc_hela-2/jrc_hela-2.zarr/em/fibsem-uint16/`) causes the ome-zarr bdv plugin to fail. Unfortunately the plugin doesn't record the full exception traceback, but here's what appeared:

<details>
<summary>traceback</summary>

```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 100MB of 2868MB (3%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1416)
	at org.embl.mobie.io.util.S3Utils.getS3Client(S3Utils.java:78)
	at org.embl.mobie.io.ome.zarr.loaders.N5S3OMEZarrImageLoader$N5S3ZarrReaderCreator.create(N5S3OMEZarrImageLoader.java:93)
	at org.embl.mobie.io.ome.zarr.loaders.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:60)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readKey(OMEZarrS3Opener.java:70)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readURL(OMEZarrS3Opener.java:53)
	at org.embl.mobie.command.OpenOMEZARRFromS3Command.openAndShow(OpenOMEZARRFromS3Command.java:53)
	at org.embl.mobie.command.OpenOMEZARRFromS3Command.run(OpenOMEZARRFromS3Command.java:62)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 26 more
Caused by: org.apache.http.HttpException: s3 protocol is not supported
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:89)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 31 more

```
</details>

The multiscale metadata for that dataset is here:

<details>
<summary>.zattrs</summary>
```json
{
    "multiscales": [
        {
            "axes": [
                {
                    "name": "z",
                    "type": "space",
                    "unit": "nanometer"
                },
                {
                    "name": "y",
                    "type": "space",
                    "unit": "nanometer"
                },
                {
                    "name": "x",
                    "type": "space",
                    "unit": "nanometer"
                }
            ],
            "coordinateTransformations": [
                {
                    "scale": [
                        1.0,
                        1.0,
                        1.0
                    ],
                    "type": "scale"
                }
            ],
            "datasets": [
                {
                    "coordinateTransformations": [
                        {
                            "scale": [
                                5.24,
                                4.0,
                                4.0
                            ],
                            "type": "scale"
                        },
                        {
                            "translation": [
                                0.0,
                                0.0,
                                0.0
                            ],
                            "type": "translation"
                        }
                    ],
                    "path": "s0"
                },
                {
                    "coordinateTransformations": [
                        {
                            "scale": [
                                10.48,
                                8.0,
                                8.0
                            ],
                            "type": "scale"
                        },
                        {
                            "translation": [
                                2.62,
                                2.0,
                                2.0
                            ],
                            "type": "translation"
                        }
                    ],
                    "path": "s1"
                },
                {
                    "coordinateTransformations": [
                        {
                            "scale": [
                                20.960000000000004,
                                16.0,
                                16.0
                            ],
                            "type": "scale"
                        },
                        {
                            "translation": [
                                7.86,
                                6.0,
                                6.0
                            ],
                            "type": "translation"
                        }
                    ],
                    "path": "s2"
                },
                {
                    "coordinateTransformations": [
                        {
                            "scale": [
                                41.92,
                                32.0,
                                32.0
                            ],
                            "type": "scale"
                        },
                        {
                            "translation": [
                                18.340000000000003,
                                14.0,
                                14.0
                            ],
                            "type": "translation"
                        }
                    ],
                    "path": "s3"
                },
                {
                    "coordinateTransformations": [
                        {
                            "scale": [
                                83.84,
                                64.0,
                                64.0
                            ],
                            "type": "scale"
                        },
                        {
                            "translation": [
                                39.300000000000004,
                                30.0,
                                30.0
                            ],
                            "type": "translation"
                        }
                    ],
                    "path": "s4"
                }
            ],
            "metadata": null,
            "name": "",
            "type": null,
            "version": "0.4"
        }
    ]
}
```
</details>

**Comment by tischi** [comment]
Dear @d-v-b ,

Thank you for reporting this!
This seems like some S3 error: `Caused by: org.apache.http.HttpException: s3 protocol is not supported`
Not sure what is going on...

@constantinpape can you maybe try opening the above data set using some python API to see if that works?

**Comment by d-v-b** [comment]
Is it possible that your plugin does not support urls formatted with the `s3://` protocol? As a user I would find this a bit surprising, since `s3://` is the standard protocol string for accessing stuff on s3, and the plugin says it supports s3... I tried again with the http:// url for that same resource (`http://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-2/jrc_hela-2.zarr/em/fibsem-uint16/`), and got the following error content:

<details>
<summary>traceback</summary>

```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 83MB of 2761MB (3%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 8XBC1VWCWY2B7RYR; S3 Extended Request ID: 4KRw2sZ8DdH0x5Bp30e6vhDOWnbVCGZOc2jMwT8JK0J7gOWyL375pwv6aJYzGDC1JFmArVSZrM8=; Proxy: null), S3 Extended Request ID: 4KRw2sZ8DdH0x5Bp30e6vhDOWnbVCGZOc2jMwT8JK0J7gOWyL375pwv6aJYzGDC1JFmArVSZrM8=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1416)
	at org.embl.mobie.io.util.S3Utils.getS3Client(S3Utils.java:78)
	at org.embl.mobie.io.ome.zarr.loaders.N5S3OMEZarrImageLoader$N5S3ZarrReaderCreator.create(N5S3OMEZarrImageLoader.java:93)
	at org.embl.mobie.io.ome.zarr.loaders.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:60)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readKey(OMEZarrS3Opener.java:70)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readURL(OMEZarrS3Opener.java:53)
	at org.embl.mobie.command.OpenOMEZARRFromS3Command.openAndShow(OpenOMEZARRFromS3Command.java:53)
	at org.embl.mobie.command.OpenOMEZARRFromS3Command.run(OpenOMEZARRFromS3Command.java:62)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more

```

</details>

For reference, neuroglancer handles both the [s3](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22x%22:%5B4e-9%2C%22m%22%5D%7D%2C%22position%22:%5B2679.46533203125%2C800%2C5958.3583984375%5D%2C%22crossSectionScale%22:15.486985096339923%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://s3://janelia-cosem-datasets/jrc_hela-2/jrc_hela-2.zarr/em/fibsem-uint16/%22%2C%22tab%22:%22source%22%2C%22name%22:%22fibsem-uint16%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22fibsem-uint16%22%7D%2C%22layout%22:%224panel%22%7D) and [http](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22x%22:%5B4e-9%2C%22m%22%5D%7D%2C%22position%22:%5B2679.46533203125%2C800%2C5958.3583984375%5D%2C%22crossSectionScale%22:15.486985096339923%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://http://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-2/jrc_hela-2.zarr/em/fibsem-uint16/%22%2C%22tab%22:%22source%22%2C%22name%22:%22fibsem-uint16%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22fibsem-uint16%22%7D%2C%22layout%22:%224panel%22%7D) versions of the url correctly.

**Comment by tischi** [comment]
Ok, thanks for letting us know! We will look into it!
I am not sure when I will find the time (our main developer of this code unfortunately left us)...
Please ping me again if it is urgent for you..
