### ISSUE TITLE
n5 reading issue after latest update

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-io#143]
Hi,

after the latest update we suffer from issues loading bdv-n5.

```
Exception in thread "Fetcher-0" java.lang.AbstractMethodError: Method org/embl/mobie/io/n5/loaders/N5ImageLoader$N5CacheArrayLoader.loadArray([J[I)Lnet/imglib2/img/basictypeaccess/DataAccess; is abstract
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:230)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:53)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)
Exception in thread "Fetcher-1" java.lang.AbstractMethodError: Method org/embl/mobie/io/n5/loaders/N5ImageLoader$N5CacheArrayLoader.loadArray([J[I)Lnet/imglib2/img/basictypeaccess/DataAccess; is abstract
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:230)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:53)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)
Exception in thread "Fetcher-2" java.lang.AbstractMethodError: Method org/embl/mobie/io/n5/loaders/N5ImageLoader$N5CacheArrayLoader.loadArray([J[I)Lnet/imglib2/img/basictypeaccess/DataAccess; is abstract
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:230)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:53)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)
Exception in thread "Fetcher-3" java.lang.AbstractMethodError: Method org/embl/mobie/io/n5/loaders/N5ImageLoader$N5CacheArrayLoader.loadArray([J[I)Lnet/imglib2/img/basictypeaccess/DataAccess; is abstract
	at org.embl.mobie.io.n5.loaders.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:230)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:53)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)

```

This was all working fine before the update to the latest mobie-io.

**Comment by imagejan** [comment]
See [this topic on zulip](https://imagesc.zulipchat.com/#narrow/stream/327354-MoBIE/topic/Fiji.20update.20breaks.20reading.20from.20zarr.20sources/near/374189614) as well as https://github.com/mobie/mobie-io/pull/142.

**Comment by ctrueden** [comment]
I built a version of mobie-io based on #142, and uploaded it to the MoBIE update site as a hot-fix. @martinschorb Can you try updating again and see whether the problem is fixed? Thanks!

**Comment by tischi** [comment]
@martinschorb @imagejan **MoBIE-beta** contains now builds of **mobie-io** and **mobie** that are based on scijava **36.0.0**; I hope that this will work. Please test it and let me know.

**Comment by martinschorb** [comment]
Confirm that it now works fine for:

- fresh virgin Fiji
- MoBIE release
- MoBIE-beta
