### ISSUE TITLE
Develop branch does not open bdv-n5-s3

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#27]
@KateMoreva 

Running this code 

```
public class OpenBDVN5S3XML {
    public static void main(String[] args) throws SpimDataException {
        SpimData spimData = new XmlIoSpimData().load("src/test/resources/prospr-myosin-n5.xml");
        BdvFunctions.show(spimData);
    }
}
```

In the `develop` brunch throws below errors. 

```
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:145)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:87)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 40 more
Caused by: java.lang.NullPointerException
	at de.embl.cba.n5.util.loaders.SetupImgLoader.prepareCachedImage(SetupImgLoader.java:106)
	at de.embl.cba.n5.util.loaders.SetupImgLoader.getImage(SetupImgLoader.java:57)
	at bdv.SpimSource.getImage(SpimSource.java:59)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:163)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:135)
	... 43 more
```

Do you know why?

**Comment by KateMoreva** [comment]
Because `develop` brunch in this repo was not even with the `main` branch. The `develop` branch here was my "helper" brunch and the same rules as for `develop` branch in `mobie-viewer-fiji` so far were not applied to this.

**Comment by tischi** [comment]
OK! I guess maybe we should also adopt the same `develop` -> `main` policy here?

**Comment by KateMoreva** [comment]
Yes, sure, I was going to. The `develop` branch should now run  OpenBDVN5S3XML.
