### ISSUE TITLE
Support ome.zarr with multiple images

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#63]
The [new example data](https://github.com/ome/ome-ngff-prototypes#data-availability) now also  has `multi-image.ome.zarr`, which contains multiple images in one container (each has their own "multiscales" metadata). We should check what happens when this is opened and think about what the correct behavior should be.
cc @tischi (discussed this today in the hackathon)

**Comment by tischi** [comment]
@constantinpape 
How does one get the *ome.zarr keys?
https://s3.embl.de/i2k-2020/ngff-example-data/v0.4

**Comment by constantinpape** [comment]
@tischi just to understand: you want to get all the objects in https://s3.embl.de/i2k-2020/ngff-example-data/v0.4 that have a ome.zarr extension?

From java, you need to use a `ListObjectRequestV2` to get all keys and then manually filter for the `ome.zarr` extension.
See for example https://github.com/saalfeldlab/n5-aws-s3/blob/master/src/main/java/org/janelia/saalfeldlab/n5/s3/N5AmazonS3Reader.java#L221-L223

**Comment by tischi** [comment]
@constantinpape Thanks! I guess I was more wondering whether we should provide a table with the keys and also what is inside the respective zarr containers? That would make it easier to consume (also doing in `ls` in a bucket with zarr containers can be very slow due to the many small files).

**Comment by constantinpape** [comment]
> Thanks! I guess I was more wondering whether we should provide a table with the keys and also what is inside the respective zarr containers?

https://github.com/ome/ome-ngff-prototypes/blob/main/README.md#single-image

**Comment by tischi** [comment]
@KateMoreva 
Could you please add a `@Test` where we open this?
https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/multi-image.ome.zarr

**Comment by constantinpape** [comment]
I tried opening it with the current version and this currently fails with some exception (see below).
However, it's not even quite clear what should happen in this case, as we need to decide which of the images to open.
For now, I see the following options:
- We don't support this for now, but give an error message that is easier to understand, like `ome.zarr files with multiple images are currently not supported
- Always open the first image
- Open a gui that allows the user to select which one to open.

I am in favor of keeping the solution here as simple as possible, as we want to move to integrate with n5-imglib2-metadata (see #61) and will likely need to adapt the strategy for dealing with multiple images per ome.zarr for this.

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.io.ome.zarr.util.N5ZarrImageReaderHelper.getN5DatasetAttributes(N5ZarrImageReaderHelper.java:30)
	at org.embl.mobie.io.ome.zarr.readers.N5S3OmeZarrReader.getZArrayAttributes(N5S3OmeZarrReader.java:171)
	at org.embl.mobie.io.ome.zarr.readers.N5S3OmeZarrReader.getDatasetAttributes(N5S3OmeZarrReader.java:176)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getDatasetAttributes(N5OMEZarrImageLoader.java:246)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:188)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:138)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:126)
	at org.embl.mobie.io.ome.zarr.loaders.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:59)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readKey(OMEZarrS3Opener.java:41)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readURL(OMEZarrS3Opener.java:24)
	at org.embl.mobie.viewer.command.OpenOMEZARRFromS3Command.openAndShow(OpenOMEZARRFromS3Command.java:22)
	at org.embl.mobie.viewer.command.OpenOMEZARRFromS3Command.run(OpenOMEZARRFromS3Command.java:31)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

**Comment by tischi** [comment]
I thought we just return a `SpimData` object that contains everything. This should work as `SpimData` essentially is a list of `Source`s which can have all different dimensions.

@KateMoreva would that be difficult to implement?

But throwing an informative error is also OK for me for now.

**Comment by constantinpape** [comment]
> I thought we just return a `SpimData` object that contains everything. This should work as `SpimData` essentially is a list of `Source`s which can have all different dimensions.

From the implementation side that would be fine with me.

But that doesn't fully solve the issue on the user side though: it's still unclear what to do when a user opens such an ome.zarr with BDV, because it may not make sense to display the images in the same coordinate space.

**Comment by KateMoreva** [comment]
There is an issue with reading the correct metadata (path to it, to be precise) for each source. I am investigating it.

**Comment by tischi** [comment]
> But that doesn't fully solve the issue on the user side though: it's still unclear what to do when a user opens such an ome.zarr with BDV, because it may not make sense to display the images in the same coordinate space.

Yes, but I think that's a rabbit hole (i.e. needs potentially loooong discussions). For now, I would just open everything, assuming that stuff in the same container lives in the same coordinate system.

**Comment by constantinpape** [comment]
> Yes, but I think that's a rabbit hole (i.e. needs potentially loooong discussions). For now, I would just open everything, assuming that stuff in the same container lives in the same coordinate system.

Yeah, this is quite complex. So I agree that we have two options for now:
- open everything in the viewer, just assume that it's in the same coordinate system
- throw a clear error message when trying to open this in BDV.

Both are fine with me.

**Comment by tischi** [comment]
> open everything in the viewer, just assume that it's in the same coordinate system

I think we should do this.

**Comment by KateMoreva** [comment]
The issue was mostly with the dataset itself. Code in the `develop` will open only first of the `multiscales`, code in the [PR](https://github.com/mobie/mobie-io/pull/67) will open all `multiscales` at once.

**Comment by KateMoreva** [comment]
> @KateMoreva 
> 2. Did you add a test for opening this? https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/multi-image.ome.zarr

S3 data needs to be changed. 

> 3. Should I merge the PR? Looks good to me.

There is a small issue with the names:

![image](https://user-images.githubusercontent.com/48569608/153862027-2f1cd8f6-4b7b-4f02-a749-7b39604f606e.png)

We have only one name, although there should be several `multiscales`.

**Comment by constantinpape** [comment]
> S3 data needs to be changed.

I have just updated it. So it would be good if you can add a test for this to #67.

> 
> There is a small issue with the names:

I think that this is all handled correctly already: all 4 images are available in the BDV menu (`p`) and can be selected, deselected etc.:
![image](https://user-images.githubusercontent.com/4263537/153864723-12cdb842-f628-4d5a-b784-5da8c5459007.png)

**Comment by KateMoreva** [comment]
> > S3 data needs to be changed.
> 
> I have just updated it. So it would be good if you can add a test for this to #67.

There is a test (for s3) : ` public void multiImg() throws IOException {}`

**Comment by constantinpape** [comment]
Implemented in #67. Thanks @KateMoreva.
