### ISSUE TITLE
Error opening OME-Zarr v0.2

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#73]
@KateMoreva 
Could you please have a look why we get an error when opening this file?
`/g/cba/exchange/ome-zarr/2022/v0.2-mobie-error.zarr`

```
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 475MB of 8405MB (5%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.io.ome.zarr.util.ZArrayAttributes.getDatasetAttributes(ZArrayAttributes.java:69)
	at org.embl.mobie.io.ome.zarr.readers.N5OmeZarrReader.getDatasetAttributes(N5OmeZarrReader.java:232)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getDatasetAttributes(N5OMEZarrImageLoader.java:248)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:185)
....
```

**Comment by constantinpape** [comment]
Just for some context: this is an ome.zarr file with format version 0.2. And we are not 100% sure if there is an issue with MoBIE opening version 0.2 files in general or something wrong with this particular file.

**Comment by KateMoreva** [comment]
The problem was that there was no information about compression. [PR](https://github.com/mobie/mobie-io/pull/75) fixes this issue.

**Comment by constantinpape** [comment]
@tischi I have merged #75 where this should be fixed. Could you make sure to also include this in the release?

**Comment by tischi** [comment]
ping @constantinpape @K-Meech @KateMoreva ☝️

**Comment by constantinpape** [comment]
> I wonder whether we should be more generous with bumping the versions in mobie-io and mobie-fiji. What about whenever we merge something as significant as a bug fix also bump the minor version? Then it is easier to see, e.g., whether what we ship with Fiji is the same thing as what we have somewhere else.

I agree, we can bump the version more frequently for smaller fixes. But note that you can also bump the patch version, i.e. the `z` in `x.y.z`. Especially when a project still has a zero major (`x`) version it's best practice to bump the patch version frequently, and bump the minor version (`y`) when something in the design changes or new functionality is added.

**Comment by tischi** [comment]
Sorry, I meant the patch version!

**Comment by K-Meech** [comment]
I think this was fixed by @KateMoreva here: https://github.com/mobie/mobie-io/pull/75. I'm not sure there's a test though?

**Comment by constantinpape** [comment]
Yes, I couldn't find a test either. I will close this for now; I will open another issue about tests since it would be good to systematize this a bit; but this can wait till after the release.
