### ISSUE TITLE
Ome zarr v0.3 reading is broken

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#76]
@KateMoreva it looks like opening ome.zarr v0.3 is not working any more, see the error below when I try to open `https://s3.embl.de/i2k-2020/ngff-example-data/v0.3/zyx.ome.zarr`. Could you please look into fixing this AND add tests that check that all the ome.zarr files in `https://s3.embl.de/i2k-2020/ngff-example-data/v0.3` can be loaded?

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $[0].axes[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at org.janelia.saalfeldlab.n5.GsonAttributesParser.parseAttribute(GsonAttributesParser.java:78)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.getAttribute(AbstractGsonReader.java:129)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:267)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:183)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:134)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:122)
	at org.embl.mobie.io.ome.zarr.loaders.N5S3OMEZarrImageLoader.<init>(N5S3OMEZarrImageLoader.java:59)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readKey(OMEZarrS3Opener.java:41)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrS3Opener.readURL(OMEZarrS3Opener.java:24)
	at org.embl.mobie.viewer.command.OpenOMEZARRFromS3Command.openAndShow(OpenOMEZARRFromS3Command.java:22)
	at org.embl.mobie.viewer.command.OpenOMEZARRFromS3Command.run(OpenOMEZARRFromS3Command.java:31)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $[0].axes[0]
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:88)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 30 more
```

**Comment by K-Meech** [comment]
This might be due to changes I made - so I'll also take a quick look

**Comment by KateMoreva** [comment]
> Thanks @KateMoreva! I was using this for writing, as I need to have a `List<ZarrAxis>` in this class to be able to write v0.4. I'll look into this, and find another way around it

I almost fix this:)

For reading, we should not use 
```
    @SerializedName(value = "axes")
    public List<ZarrAxis> zarrAxisList;
```
for writing, we need to convert List<ZarrAxis> zarrAxisList to the ZarrAxes. Thus there would not be problems with v3 and v4 reading and writing.

**Comment by K-Meech** [comment]
I think this was all fixed by @KateMoreva here: https://github.com/mobie/mobie-io/pull/78
