### ISSUE TITLE
N5 file can't be opened from private S3 bucket with shared queue

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-io#83]
Opening an n5 file in a private bucket like so works:
```
final ImageJ imageJ = new ImageJ();
        imageJ.ui().showUI();
        try {
            S3Utils.setS3AccessAndSecretKey( new String[]{"acess","key"} );
            SpimData spimData = (SpimData) new SpimDataOpener().openSpimData("path/to/bucket/image.xml", ImageDataFormat.BdvN5S3);
            BdvFunctions.show(spimData);
        } catch ( SpimDataException e) {
            e.printStackTrace();
        }
```
but with a shared queue doesn't. Same as above but with:
```
SpimData spimData = (SpimData) new SpimDataOpener().openSpimData("path/to/bucket/image.xml", ImageDataFormat.BdvN5S3, new SharedQueue( N_FETCHER_THREADS ));
```
Errors with:
```
mpicbg.spim.data.SpimDataException: Error while trying to read spimDataServer returned HTTP response code: 403 for URL: https://s3.embl.de/meechan-user/test/images/bdv-n5-s3/mri-stack.xml
	at org.embl.mobie.io.SpimDataOpener.openBdvN5S3(SpimDataOpener.java:110)
	at org.embl.mobie.io.SpimDataOpener.openSpimData(SpimDataOpener.java:69)
	at run.Temp.main(Temp.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
```

Related to: https://github.com/mobie/mobie-viewer-fiji/issues/621

**Comment by K-Meech** [comment]
@KateMoreva - would you have time to look into this?

**Comment by KateMoreva** [comment]
> @KateMoreva - would you have time to look into this?

Yes, I'll look into this today or/and tomorrow.

**Comment by K-Meech** [comment]
This is fixed now :)
